### ISSUE TITLE
Hi! Are you planning on supporting `cors.now.sh/` in the long run?

### ISSUE THREAD

**Issue by felix91gr** [hemanth/ama#1]
Hi man, I was just wondering about this.

I have been trying for days (DAYS!) to use a non-cors API and... uff. When it _just worked_ using `cors.now`, I was very pleased :)
And of course, I was trying to fetch from the **xkcd** API :laughing: just as your example.

So, I want to ask you before I ship this program... will you still support it in the upcoming years? :P 

Thanks!

**Comment by hemanth** [comment]
Glad you liked it.

Yes, I will be!

**Comment by felix91gr** [comment]
Awesooome :heart: Thank you!

I'll send you a link whenever it's ready ;)
