### ISSUE TITLE
Where would you live if you could live anywhere?

### ISSUE THREAD

**Issue by sindresorhus** [hemanth/ama#10]

**Comment by hemanth** [comment]
Pluto! It was my fav planet as a kid, well it's no more a planet :crying_cat_face: 

Jokes apart, on Earth, to be very frank I haven't spent quality amount of time outside India, if US it would be [Virginia](https://en.wikipedia.org/wiki/Virginia) is EU it would be London and finally [Netherlands](https://en.wikipedia.org/wiki/Netherlands) :smile:
