### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [hemanth/ama#11]

**Comment by hemanth** [comment]
As a kid, I always had imagined that computers are devices which would answer any questions we have, solves any problem we have in life! 

I was in 6th grade (11years old), when I first saw a computer and did some `QBasic` programming on it.

In 9th grade did some C programming, until which I was on window$ and then my first ever experience with GNU/Linux was with Knoppix live CD where I feel in love with `bash` scripting and some `gtk` programming.

During my college I was on and off with programming (not very serious) and during my engineering days I was contributing to `ubuntu` on launchpad, brainstroming and later on meet Github :)
