### ISSUE TITLE
How did you get involved in Yeoman?

### ISSUE THREAD

**Issue by nihar108** [hemanth/ama#14]
How did you get to know about it? How did you start contributing to it?

**Comment by hemanth** [comment]
At the inception of yeoman, I was hanging out in #yeoman IRC and pinged  @paulirish and @addyosmani asking if a setup script would be useful, later that was converted to a node script with shelljs then it was `yeoman` on npm and later it was `yo` from giants like @sindresorhus and @SBoudrias

On [Dec 23, 2013](https://github.com/yeoman/yeoman/issues/1248#issue-24700744) Addy added me to the core team after which I contributed in multiple aspects and later become the maintainer of [generator-node](https://github.com/yeoman/generator-node)

**Comment by paulirish** [comment]
Oh man that bash script was epic.

**Comment by hemanth** [comment]
Heh heh yeah! :+1:
