### ISSUE TITLE
What are transducers ? (can u explain with an example in js )

### ISSUE THREAD

**Issue by annamalai-saro** [hemanth/ama#19]

**Comment by hemanth** [comment]
`CSP and transducers` ? 

Any reason for changing the title? :wink:

**Comment by annamalai-saro** [comment]
Am pretty clear abt Immutable structures after seeing Facebook dev channel in youtube.... :stuck_out_tongue_closed_eyes:  

Regarding the question ... As far as I know ...CSPs are more like go channels and transducers are like composing multiple functional map ,reduce etc ..

What so special about transducers ? :grin:

**Comment by hemanth** [comment]
`transducers` roots deep into `Clojure` 

It's basically transformation from one reducing function to another.

```
(whatever, input -> whatever) -> (whatever, input -> whatever)
```

__What's special?__

Well, it helps us to compose function is a better way.

Say in JS

```js
[1,2,3,4].map( (n) => n +1)
```

vs

```js
map( (n) => n+1, [1,2,3,4])
```

The second one is more closer to transducers and by passing function as the first parameter, composing it gets easier and also helps in meaningful currying.

**Comment by annamalai-saro** [comment]
Cool !
