### ISSUE TITLE
What are your thoughts on Rust and Golang?

### ISSUE THREAD

**Issue by skippednote** [hemanth/ama#2]
Do you plan to look into anything other than JavaScript?

**Comment by hemanth** [comment]
Well my first job was on ROR, then did work on Python, PHP, Perl and realised that with JS one could easily work both on the server and client environments.

If JS is solving your problems I don't see a need to switch to Golang.It's worth playing around rust.

As a whole it's always good to work on multiple languages and get the best of all of them to your primary lang of choice.
