### ISSUE TITLE
How do you manage your time? Office, home, contributing to open source, yeoman..etc. How many hours do you sleep per day?

### ISSUE THREAD

**Issue by ilayarajas** [hemanth/ama#21]

**Comment by hemanth** [comment]
Well, I feel I don't really manage my time well, when compared to few of my friends from yeoman like @sindresorhus @passy @addyosmani.

My working hours consume `8hrs` of my day time, commute will eat up around `3hrs` on an average.

I'm left with `12hrs` out of which I sleep around `7-8hrs`, so finally if I'm left with just `4hrs` for rest of the things.

To be very frank, I made all this calculation after you asked the question, only way to manage time is not to look at it till you reach your goal :wink: 

On a serious note, keep pushing yourself a bit harder everyday, make it a routine and then it must get easier. (How easy, is still a very relative term)

**Comment by chadfurman** [comment]
+1 for focus on your goal not on the time
