### ISSUE TITLE
I have read ' for loop ' is faster than ' for in ' loop in javascript ? But I did a perf and 'for in' seems faster ... why ?

### ISSUE THREAD

**Issue by annamalai-saro** [hemanth/ama#24]
![screen shot 2015-08-08 at 11 25 21 am](https://cloud.githubusercontent.com/assets/5235065/9149274/57182edc-3dc0-11e5-892d-b7eed312738b.png)

while(length--) is faster .....but just want to know among these two :wink: :wink:

**Comment by hemanth** [comment]
Done use `for..in` for `Array` and do checkout [jsperf](http://jsperf.com/forloops3/35) for perfs.
