### ISSUE TITLE
what is your dev setup (ide, browser, ...)

### ISSUE THREAD

**Issue by stoeffel** [hemanth/ama#3]
^^

**Comment by hemanth** [comment]
Primary machine is MBP with a odd memory:

![screen shot 2015-07-14 at 12 56 08](https://cloud.githubusercontent.com/assets/18315/8668345/c1340e32-2a27-11e5-989a-1ed604aa3042.png)

Browsers well almost all canary, nightly and stable ones ;)

IDE: Keep switching b/w vim, sublime, atom.

I'm use default terminal with [bash_it](https://github.com/Bash-it/bash-it) on it.

For my dot files -> https://mths.be/dotfiles

**Comment by stoeffel** [comment]
> I'm use default terminal with bash_it on it.

If tou like bashit, you should try `oh my zsh`.

**Comment by hemanth** [comment]
Yeah I have tired that too, have emotional attachments with bash :)

**Comment by bogas04** [comment]
Hey!

What about in 2016 ? :smile:

**Comment by hemanth** [comment]
HyperTerm!
