### ISSUE TITLE
boilerplate generator

### ISSUE THREAD

**Issue by geraldchecka** [hemanth/ama#31]
Hi Hemanth,
I've been learning React and Webpack these days. I recently wrote a small <a href="https://github.com/geraldchecka/webpack-react-boilerplate">Webpack + React boilerplate</a> that suits my needs. The current boilerplate available on the Internet doesn't fully meets the reqs for any given project. My question is: What is it like to build a dynamic boilerplate code generator based on inputs given from the GUI by developer. It can save lot of time for individuals to drill through the Internet to build scripts. Please let me know what you think. If you think it's not a bad idea, I wanted to do it.

**Comment by hemanth** [comment]
You must have a look at [yeoman-generator](http://tagtree.tv/yeoman-generator) and start contributing to [yeoman-app](https://github.com/yeoman/yeoman-app) <- is a GUI.

**Comment by geraldchecka** [comment]
ohhh. ok. thank you.
