### ISSUE TITLE
Do you think that Coffeescript is slowing down?

### ISSUE THREAD

**Issue by faustinoaq** [hemanth/ama#32]
[Javascript comic image](http://www.commitstrip.com/wp-content/uploads/2015/09/Strip-Prendre-le-train-en-marche-650-finalenglish1.jpg)

I like the new es6, but also I like functions without braces and lines without semicolons.
I think that Coffeescript need something new.

My excuses:
https://github.com/sindresorhus/awesome/issues/323
https://github.com/hemanth/coffeescript-equivalents-in-es6
https://github.com/lydell/frappe

PD: The community is working, but jashkenas is busy
https://twitter.com/jashkenas/status/646003224395280384

**Comment by hemanth** [comment]
I definitely stand with @sindresorhus here.

This is what @douglascrockford had to say about it:

> One of my favorites along those lines is a new little language called CoffeeScript, which takes the good parts -- not even all of the good parts, but a nice little language -- and comes up with groovy new syntax for it, which is minimal. It's almost like dandelions: little fluffs of programs that do everything that conventional JavaScript programs do. You can't do anything in that language that you can't do in JavaScript, so it's all cosmetic. I don't know if all or much of that will find its way into JavaScript, because I'm not sure there's enough of a payoff there. But just as an experiment, as a design exercise, I think it's a brilliant piece of work. I'm excited to see stuff like that happening.

He had also mentioned in one of the conference to play with it and not even think of using it in production.

That said and done, ruby schoolers kina like it ;)

**Comment by faustinoaq** [comment]
Ok
![toBe](http://sstatic.net/img/life-instructions.png)

**Comment by hemanth** [comment]
:+1:
