### ISSUE TITLE
What do you think about this?

### ISSUE THREAD

**Issue by amitmerchant1990** [hemanth/ama#35]
Some days ago, I came across this article.

http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos

What are your thoughts about the same? Do developers needs to be that much emotional?! your thoughts?

**Comment by hemanth** [comment]
Well, emotions are too very personal, we can't really draw lines there.

I thoughts would be very close to [this](http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm?utm_source=nodeweekly&utm_medium=email).

P.S: Do read about [kik](https://medium.com/@mproberts/a-discussion-about-the-breaking-of-the-internet-3d4d2a83aa4d#.7zjf8e7hh).
