### ISSUE TITLE
Is College helpful?

### ISSUE THREAD

**Issue by abhisack** [hemanth/ama#36]
How helpful the things you learnt at your college are now, when you're working with the web technologies?

**Comment by hemanth** [comment]
> Is College helpful?

Well, I would say it depends on where you are.

Some places where there are abundant of human resources, a degree is on of the factors that draw a line.

But on the contrast, if you think college isn't teaching you anything new and have a plan of experimenting on starting up something new of your own and confident of doing it, try it.

In terms of learning, well, it's up to you on how much you go off track to learn things out of your syllabus.
