### ISSUE TITLE
What happened to Bangalore JS?

### ISSUE THREAD

**Issue by geraldchecka** [hemanth/ama#37]
I used to attend Bangalore JS meetups in my early days. Talks used to super cool, high on quality and very informative. Why did Bangalore JS die? The city doesn't hear anything about it these days.

**Comment by hemanth** [comment]
It's not dead, let us bring it back!

**Comment by siddharthkp** [comment]
@hemanth, how can I help?

**Comment by hemanth** [comment]
Will let you know sooon!

**Comment by geraldchecka** [comment]
Count me in

**Comment by hemanth** [comment]
Sure

**Comment by kundansingh1** [comment]
Count me in as well if any contribution or volunteering required.
