### ISSUE TITLE
How to become a best programmer. 

### ISSUE THREAD

**Issue by ChaudhariPrasad** [hemanth/ama#39]
I am trying to learn  c++, python, Java Script but somehow loose my way after starting. I want to master these languages but loose my interest after going through few chapters.  I want to be in position where i can start understanding other people code, start contributing to open source repo and at the same time enjoy, feel satisfied during this whole process. I am basically an Electronics and Telecommunication engineer  so dont have any formal education of computer science but i want be in position to understand all that data structure, algorithms  stuff.. Currently i am working as software professional with work related to c++.

**Comment by hemanth** [comment]
> I am trying to learn c++, python, JavaScript but somehow loose my way after starting

Good, play around with many languages and select the one you really like.

> I want to master these languages but loose my interest after going through few chapters.

Mastering things is very relative, just pick up the good parts from each of them.

> I want to be in position where i can start understanding other people code, start contributing to open source repo and at the same time enjoy, feel satisfied during this whole process.

You will enjoy it when you stop thinking of being a master ;) [Life is too short to master anything]

>  I am basically an Electronics and Telecommunication engineer so dont have any formal education of computer science.

Doesn't matter, I have seen general physicians contributing to open source. 

> Currently i am working as software professional with work related to c++.

As your work is related to C++, I would suggest to pick up related open source projects and start working on it, look at the issues, comment, understand, send a PR, get a review, improve.

--
Wish you good luck!
