### ISSUE TITLE
How did you get into open source ?

### ISSUE THREAD

**Issue by shidhincr** [hemanth/ama#4]
I haven't seen much of the other developers from India who are active as you. How did you get into open source ?

How do you manage your side projects ?

**Comment by hemanth** [comment]
Well, I have been lurking around in Github from Jul 25, 2008, I was contributing to Ubuntu from 2005ish over launchpad, my first major contribution was for [diaspora](https://github.com/diaspora/diaspora) and later on [yeoman](http://yeoman.io)

I manage my side projects by collaborating with humans! (:

**Comment by stoeffel** [comment]
> I manage my side projects by collaborating with humans! (:

:+1: it's always cool to collab with you (currently manly on https://github.com/1-liners/1-liners and https://github.com/npm-scripts/scripts)

**Comment by hemanth** [comment]
Thanks :blush:
