### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [hemanth/ama#9]
Screenshot please. I ask everyone this as it can tell a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by hemanth** [comment]
![2015-07-14](https://cloud.githubusercontent.com/assets/18315/8674780/93d2a97c-2a5d-11e5-8746-dc0fd39bb0ec.jpg)

The wallpaper was a photo I [snapped](https://instagram.com/p/4_0rxKse4k/?taken-by=gnumanth) lately with my nexus 5 :)
